# 1. What is the total revenue generated?

SELECT
    SUM(order_items.quantity * order_items.price) AS total_revenue
FROM order_items;


# 2. What are the top-selling products?

SELECT
    products.product_name,
    SUM(order_items.quantity) AS units_sold
FROM order_items
JOIN products
    ON order_items.product_id = products.product_id
GROUP BY
    products.product_id,
    products.product_name
ORDER BY
    units_sold DESC;


# 3. Which products generated the most revenue?

SELECT
    products.product_name,
    SUM(order_items.quantity * order_items.price) AS total_revenue
FROM order_items
JOIN products
    ON order_items.product_id = products.product_id
GROUP BY
    products.product_id,
    products.product_name
ORDER BY
    total_revenue DESC;


# 4. Which customers spent the most?

SELECT
    customers.customer_name,
    SUM(order_items.quantity * order_items.price) AS total_spent
FROM customers
JOIN orders
    ON customers.customer_id = orders.customer_id
JOIN order_items
    ON orders.order_id = order_items.order_id
GROUP BY
    customers.customer_id,
    customers.customer_name
ORDER BY
    total_spent DESC;


# 5. Which city generated the most sales?

SELECT
    customers.city,
    SUM(order_items.quantity * order_items.price) AS total_sales
FROM customers
JOIN orders
    ON customers.customer_id = orders.customer_id
JOIN order_items
    ON orders.order_id = order_items.order_id
GROUP BY
    customers.city
ORDER BY
    total_sales DESC;


# 6. What are the monthly sales trends?

SELECT
    DATE_FORMAT(orders.order_date, '%Y-%m') AS month,
    SUM(order_items.quantity * order_items.price) AS total_sales
FROM orders
JOIN order_items
    ON orders.order_id = order_items.order_id
GROUP BY
    month
ORDER BY
    month;


# 7. Which product categories generated the most revenue?

SELECT
    products.category,
    SUM(order_items.quantity * order_items.price) AS total_revenue
FROM products
JOIN order_items
    ON products.product_id = order_items.product_id
GROUP BY
    products.category
ORDER BY
    total_revenue DESC;


# 8. Which customers placed more than one order?

SELECT
    customers.customer_name,
    COUNT(orders.order_id) AS number_of_orders
FROM customers
JOIN orders
    ON customers.customer_id = orders.customer_id
GROUP BY
    customers.customer_id,
    customers.customer_name
HAVING
    COUNT(orders.order_id) > 1
ORDER BY
    number_of_orders DESC;


# 9. What is the average order value?

SELECT
    AVG(order_totals.order_total) AS average_order_value
FROM
(
    SELECT
        orders.order_id,
        SUM(order_items.quantity * order_items.price) AS order_total
    FROM orders
    JOIN order_items
        ON orders.order_id = order_items.order_id
    GROUP BY
        orders.order_id
) AS order_totals;


# 10. Which customers have not placed any orders?

SELECT
    customers.customer_name,
    customers.city
FROM customers
LEFT JOIN orders
    ON customers.customer_id = orders.customer_id
WHERE
    orders.order_id IS NULL;


# 11. Which products have never been sold?

SELECT
    products.product_name,
    products.category,
    products.price
FROM products
LEFT JOIN order_items
    ON products.product_id = order_items.product_id
WHERE
    order_items.product_id IS NULL;


# 12. How many units were sold in each product category?

SELECT
    products.category,
    SUM(order_items.quantity) AS units_sold
FROM products
JOIN order_items
    ON products.product_id = order_items.product_id
GROUP BY
    products.category
ORDER BY
    units_sold DESC;


# 13. Which customer made the largest single order?

SELECT
    customers.customer_name,
    orders.order_id,
    orders.order_date,
    SUM(order_items.quantity * order_items.price) AS order_total
FROM customers
JOIN orders
    ON customers.customer_id = orders.customer_id
JOIN order_items
    ON orders.order_id = order_items.order_id
GROUP BY
    customers.customer_id,
    customers.customer_name,
    orders.order_id,
    orders.order_date
ORDER BY
    order_total DESC
LIMIT 1;


# 14. What percentage of total revenue was generated by each product?

SELECT
    products.product_name,
    SUM(order_items.quantity * order_items.price) AS product_revenue,
    ROUND(
        SUM(order_items.quantity * order_items.price)
        /
        (SELECT SUM(quantity * price) FROM order_items)
        * 100,
        2
    ) AS revenue_percentage
FROM products
JOIN order_items
    ON products.product_id = order_items.product_id
GROUP BY
    products.product_id,
    products.product_name
ORDER BY
    revenue_percentage DESC;


# 15. Which day had the highest sales?

SELECT
    orders.order_date,
    SUM(order_items.quantity * order_items.price) AS daily_sales
FROM orders
JOIN order_items
    ON orders.order_id = order_items.order_id
GROUP BY
    orders.order_date
ORDER BY
    daily_sales DESC
LIMIT 1;


# 16. Which customer placed the most orders?

SELECT
    customers.customer_name,
    COUNT(orders.order_id) AS number_of_orders
FROM customers
JOIN orders
    ON customers.customer_id = orders.customer_id
GROUP BY
    customers.customer_id,
    customers.customer_name
ORDER BY
    number_of_orders DESC
LIMIT 1;


# 17. Which category has the highest average product price?

SELECT
    products.category,
    ROUND(AVG(products.price), 2) AS average_price
FROM products
GROUP BY
    products.category
ORDER BY
    average_price DESC;


# 18. What is the average number of units purchased per order?

SELECT
    ROUND(AVG(order_quantities.total_units), 2) AS average_units_per_order
FROM
(
    SELECT
        orders.order_id,
        SUM(order_items.quantity) AS total_units
    FROM orders
    JOIN order_items
        ON orders.order_id = order_items.order_id
    GROUP BY
        orders.order_id
) AS order_quantities;


# 19. What are the top 5 highest-value orders?

SELECT
    orders.order_id,
    customers.customer_name,
    orders.order_date,
    SUM(order_items.quantity * order_items.price) AS order_total
FROM orders
JOIN customers
    ON orders.customer_id = customers.customer_id
JOIN order_items
    ON orders.order_id = order_items.order_id
GROUP BY
    orders.order_id,
    customers.customer_name,
    orders.order_date
ORDER BY
    order_total DESC
LIMIT 5;


# 20. What is the overall sales summary?

SELECT
    COUNT(DISTINCT orders.order_id) AS total_orders,
    COUNT(DISTINCT orders.customer_id) AS total_customers,
    SUM(order_items.quantity) AS total_units_sold,
    SUM(order_items.quantity * order_items.price) AS total_revenue,
    ROUND(
        AVG(order_items.quantity * order_items.price),
        2
    ) AS average_line_revenue
FROM orders
JOIN order_items
    ON orders.order_id = order_items.order_id;
